version: "3.3"

services:
    mysql:
        image: mariadb
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: flowerdb
            MYSQL_HOST: localhost
            MYSQL_ROOT_PASSWORD: password
        restart: unless-stopped
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./db/populate_db.csv:/var/lib/populate_db.csv
        ports:
            - 4000:3306
    backend:
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: flowerdb
            MYSQL_HOST_IP: mysql
        build: ./backend
        ports:
            - 5000:5000
        volumes:
            - ./backend:/app
            - /app/node_modules
        links:
            - mysql
        networks: 
            default: {}
        command: npm start
    frontend:
        environment: 
            CHOKIDAR_USEPOLLING: "true"
        build: ./frontend
        stdin_open: true
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app
            - /app/node_modules
        links:
            - backend
        networks: 
            default: {}
        command: npm start
networks:
    default:
        attachable: true
volumes:
    sql-persistence: