version: "3.8"

x-common-variables: &common-variables
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: flowerdb

services:
    mysql:
        image: mariadb
        environment:
            <<: *common-variables
            MYSQL_HOST: localhost
            MYSQL_ROOT_PASSWORD: password
        restart: unless-stopped
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 4000:3306
    backend:
        environment:
            <<: *common-variables
            MYSQL_HOST_IP: mysql
        build: ./backend
        ports:
            - 5000:5000
        volumes:
            - ./backend:/app
            - /app/node_modules
        links:
            - mysql
        networks: 
            default: {}
        command: npm start
    frontend:
        build: ./frontend
        stdin_open: true
        ports:
            - 3000:3000
        volumes:
            - ./frontend/src:/app/src
            - /app/node_modules
        links:
            - backend
        networks: 
            default: {}
        command: npm start
networks:
    default:
        attachable: true
